### PR TITLE
Add Rotations manifold

### PR DESCRIPTION
**Pull request by tingelst**
As  per issue #40, this PR implements a first step towards adding the rotation manifold SO(n)^k to pymanopt. The code is a direct port from [rotationsfactory(n,k)](https://github.com/NicolasBoumal/manopt/tree/master/manopt/manifolds/rotations).

### CODE REVIEW

**Comment by j-towns** [comment]
Hey there, thanks very much for the pr. Can you change [this comment](https://github.com/tingelst/pymanopt/blob/928ceb268024a547885ddb33f3f7ec37bf3492b8/pymanopt/manifolds/rotations.py#L3-L41) into a docstring, with the code snippets changed to match the Python implementation? For example
```matlab
function M = rotationsfactory(n)
```
should be
```python
M = Rotations(n)
```
If you have time, it would be great if you could put one or two proper code examples, copied and pasted from the Python interpreter, in the style of [this docstring](https://github.com/pymanopt/pymanopt/blob/master/pymanopt/manifolds/fixed_rank.py#L14-L84).

Pycodestyle is also raising a couple of errors (which is why the travis-ci tests are failing):
```
pymanopt/manifolds/rotations.py:65:55: E262 inline comment should start with '# '
pymanopt/tools/multi.py:44:1: E302 expected 2 blank lines, found 1
```
If you can fix those and the docstring I'll merge.

**Comment by tingelst** [comment]
That's great! I will continue work on the PR during this week.

**Comment by tingelst** [comment]
@j-towns: The implementation of the Rotations manifold should now be feature complete. I have also added an example file to the examples folder. Tests are missing though. I am working on these as of now. 

Could you do a quick review?

**Comment by j-towns** [comment]
This all looks good to me so I'm gonna merge. It would be great if we could also fully test the methods. Testing some of the methods is a little tricky without just reimplementing the method, but I still think that is much better than having nothing. If you have time it would be fantastic if you could do something as thorough as [this](https://github.com/pymanopt/pymanopt/blob/master/tests/test_manifold_fixed_rank.py).

**Pull request merged**
