### PR TITLE
Add unitaries manifold

### PR DESCRIPTION
**Pull request by htwei17**
A Unitaries manifold class is added ported from the counterpart in Manopt, slightly modified to the templated of existing Rotations class in 0.2.5 version.

### CODE REVIEW

**Comment by nkoep** [comment]
Thanks for the PR! I will try to review this sometime next week :crossed_fingers:

**Comment by nkoep** [comment]
Thanks for taking the time to update your PR. Considering the close connection to the `SpecialOrthogonalGroup` manifold, however, I would prefer it if we could follow the example of the `Grassmann` and `ComplexGrassmann` manifold implementations and isolate the shared parts to a `_SpecialGroupBase` mixin; the majority of methods in `Unitaries` (which I would prefer to call `SpecialUnitaryGroup` for consistency btw) would work just fine with real-valued inputs so that we could re-use them for both groups.

I'm happy to work on this if you do not find the time to do it. Just let me know and I'll take it from here. Again, thanks for your PR :bow:

**Comment by Nottforestfc** [comment]
> Thanks for taking the time to update your PR. Considering the close connection to the `SpecialOrthogonalGroup` manifold, however, I would prefer it if we could follow the example of the `Grassmann` and `ComplexGrassmann` manifold implementations and isolate the shared parts to a `_SpecialGroupBase` mixin; the majority of methods in `Unitaries` (which I would prefer to call `SpecialUnitaryGroup` for consistency btw) would work just fine with real-valued inputs so that we could re-use them for both groups.
> 
> I'm happy to work on this if you do not find the time to do it. Just let me know and I'll take it from here. Again, thanks for your PR 🙇

Hi Niklas, So happy to hear back from you! I am glad about all you pointed out. Unfortunately, I am having some personal issues s.t. I am not able to make these changes right now - so it is terrific that you are willing to take it. Apologies for any inconvenience.

**Comment by nkoep** [comment]
Closing this in favor of #232.

**Pull request closed without merging**
