### PR TITLE
Adding Poincare ball model + tests

### PR DESCRIPTION
**Pull request by qrebjock**
Hi all,

I implemented the Poincare ball model for hyperbolic geometry (in any dimension) and the corresponding tests.
This is *not* a Riemannian embedded submanifold, so the Riemannian gradient and Hessian are not computed automatically.
For this reason I found it hard to set up tests for the functions `egrad2rgrad` and `ehess2rhess`; let me know if you have ideas.

Best,
Quentin

### CODE REVIEW

**Comment by kellertuer** [comment]
Cool. I am not that familiar with the egrad/ehess implementation in Python, but they might maybe just not exist without an embedding?

If you want you could also transfer what we recently did: conversion from Poincaré ball to hyperboloid model (though in a different language)
https://juliamanifolds.github.io/Manifolds.jl/stable/manifolds/hyperbolic.html#Base.convert-Tuple{Type{HyperboloidPoint},PoincareBallPoint}
and the inverse
https://juliamanifolds.github.io/Manifolds.jl/stable/manifolds/hyperbolic.html#Base.convert-Tuple{Type{PoincareBallPoint},Any}

as well as for the tangent vectors (i.e. the oush forwards of these methods). Then you can at least “reuse” hyperboloid gradients.

**Comment by qrebjock** [comment]
Hello,

Thanks for your comment. I think my wording was not clear. This manifold is embedded in the Euclidean space (R^{k x n}), but it is not a Riemannian embedded submanifold of that space. So the gradients and Hessians are not computed automatically via projections.
I calculated the conversion functions and checked that the Taylor expansions are coherent. But my point was just that setting up tests for these formulas is not so obvious.

**Comment by kellertuer** [comment]
Thanks for the explanation, so it's some Euclidean computation on R^{k x n} (which is not the embedding, especially no isometric one), so there is no project but a conversion. Interesting to learn :)

**Comment by andberger** [comment]
A suggestion as to handling the case when computing the distance between a point and itself, since it currently produces a `nan`:

` columns_dist = np.arccosh(max(1, 1 + 2 * norms2_difference / ((1 - norms2_X) * (1 - norms2_Y))))`

**Comment by nkoep** [comment]
Hi @qrebjock! Sorry about not getting back to you on this PR sooner! There's been quite a few changes in the public pymanopt API and conventions since you proposed this PR. Let me know if you have time to update the PR (and whether you're still interested in contributing it). If not, I'm more than happy to update it myself.

On a related note, do you happen to have a good reference for the implementation contributed here? I'd also be very interested to learn a little about examples where this manifold comes up in applications if you have any. :bow:

**Comment by nkoep** [comment]
Hi @qrebjock! Sorry about not getting back to you on this PR sooner! There's been quite a few changes in the public pymanopt API and conventions since you proposed this PR. Let me know if you have time to update the PR (and whether you're still interested in contributing it). If not, I'm more than happy to update it myself.

On a related note, do you happen to have a good reference for the implementation contributed here? I'd also be very interested to learn a little about examples where this manifold comes up in applications if you have any. :bow:

**Comment by kellertuer** [comment]
Hi Niklas,
at least for our https://juliamanifolds.github.io/Manifolds.jl/v0.5/manifolds/hyperbolic.html#poincare_ball Poincaré ball, we used (but I just noticed its not references) John M. Lee, Introduction to Riemannian Manifolds, 2nd editions, p. 62.

**Pull request merged**
