### PR TITLE
Add singledispatch-based internal numerics package

### PR DESCRIPTION
**Pull request by nkoep**

### CODE REVIEW

**Comment by antoinecollas** [comment]
Well done! It is elegant and seems to be the way to go. Should we merge this in #245?

**Comment by sweichwald** [comment]
Nice!

What do we do about `numpy` vs `autograd.numpy`? The latter is thinly wrapping the former with few minor alterations (e.g. [here](https://github.com/HIPS/autograd/blob/1bb5cbc21d2aa06e0c61654a9cc6f38c174dacc0/autograd/numpy/numpy_wrapper.py#L83)).

**Comment by nkoep** [comment]
Let me develop this idea a bit further and survey some more functions that we need to support so see if there are any edge cases that might trip us up before merging it, @antoinecollas. In fact, maybe it's best to keep these computational backend changes in this PR here until it's ready, while the other one can deal with the changes necessary for the autodiff code afterwards.

Autograd is in fact one of those tricky edge cases (as is jax). While the libraries wrap arrays in their own boxed types, they do accept regular numpy arrays which only get promoted to boxed types when a library function is called. So we'd be fine when users define a cost function like `def cost(x): return jnp.linalg.norm(x) ** 2`, but not for things like `def cost(x): return sum(x ** 2)`. Let's see how far we can push this idea.

Generally speaking I'm in favor of using type annotations going forward, @sweichwald :+1:

**Comment by NicolasBoumal** [comment]
Thanks, @nkoep!

This issue of having to dispatch calls to various numerical backends is fairly common. Would it make sense to use an existing package to deal with that (with the risks that entails) rather than developing a new one here (avoiding the risks that entails)?

For example, here is one: https://github.com/jcmgray/autoray   (just the first result when googling "python singledispatch numerics backends numpy jax pytorch").

**Comment by antoinecollas** [comment]
We discussed this in #245. The problem with relying on autoray or eagerpy is that we will have a new dependency and it becomes harder to maintain (dependent on a change of API, do PR in autoray/eagerpy to add functions, etc...). Also, we don't use that many functions. So doing ourselves seems do-able and using these libraries is quite over-engineering in my opinion.

**Comment by nkoep** [comment]
Closing this in favor of #252 for easier collaboration.

**Pull request closed without merging**
