### PR TITLE
Rename backend decorators + a few additional minor changes

### PR DESCRIPTION
**Pull request by nkoep**
This PR introduces a few "breaking" changes in the lead-up to Pymanopt 1.0.0 in a similar vain to #106.

Highlights:
- Add `retraction` argument to constructor of `SpecialOrthogonalGroup` class that allows switching between QR-based and polar retraction
- Raise an error if the initial simplex passed to `NelderMead.solve` is not of the correct length
- Provide default implementation of `Manifold.tangent` that simply raises a `NotImplementedError` rather than omitting the method altogether
- Fix bug in (unfortunately untested) `ehess2rhess` method of `ComplexCircle` class 834ceeb334d2b3503933cacf7e2c72ccec73d18b
- Fix unit test `test_exp_log_inverse` of sphere manifold 4973f861bcd7b38bce6b2b253d2a982ac0b681fa
- Rename function decorators for backends from `Autograd` to `autograd`, etc.
- Rename `Callable` backend decorator to `numpy` to be more in-line with the rest of the decorators

The last two points are undoubtedly the most severe (user-facing) changes (even if it's just a simple renaming), but in the spirit of #155 we decided to give ourselves the freedom to redesign a lot of pymanopt's API considering that the next release will bump the major version.

### CODE REVIEW

**Comment by kellertuer** [comment]
One could even put the `retraction` keyword argument into the `retr` function (and let it default to the value from the manifold)? This way) or would that be a performance issue?
For example in Julia we have a function [default_retraction_method](https://juliamanifolds.github.io/Manifolds.jl/stable/interface.html#ManifoldsBase.default_retraction_method-Tuple{AbstractManifold}), which by default (i.e. if not specified explicitly for a manifold) returns the exponential, but can be set to something else (especially if no exp is available).
The central function [`retract(M,p,X)`](https://juliamanifolds.github.io/Manifolds.jl/stable/interface.html#ManifoldsBase.retract-Tuple{AbstractManifold,%20Any,%20Any}) has a fourth optional argument indicating the retraction (by default the just mentioned default retraction)

I saw your renaming ideas – nice! We also have `retract` and `zero_vector`as well, but we kept `dist`, `exp` and `log`.
Our `project` works with either two arguments (M,p) to project a point on the manifold or with three (M,p,X) to project X onto TpM – same idea for embed. For random we plan the same but that (separate) package is still under construction).

For the gradient, we just use `gradient` and the Euclidean one is specified by plugging in the Rn as fist argument (ok that might be different here since you have manifold objects).
For the gradient conversion (e2r) we do not have an own function, since it always consists of (a) projection (in the embedding onto the tangent space) and metric conversion (i.e. changing the Reisz representer of the differential from one metric to another, see [change_representer](https://juliamanifolds.github.io/Manifolds.jl/latest/manifolds/metric.html#Manifolds.change_representer-Tuple{AbstractManifold,%20AbstractMetric,%20Any,%20Any}) for the function and [thetutorial on AD](https://manoptjl.org/stable/pluto/AutomaticDifferentiation.html) for details). Just in case that if you are redesigning this anyways, think whether that might be a good model.

Indeed for one case I switched that order (to changing the representer and then projecting with the metric from TpM extended into the embedding) since that was described by Gao & Absil – but for that I just redefined one `gradient` function.

Sorry for the longer post, but I saw the roadmap and maybe some of these ideas are useful. Cool that there is so much happening these days in pymanopt :)

**Comment by nkoep** [comment]
> Sorry for the longer post, but I saw the roadmap and maybe some of these ideas are useful. Cool that there is so much happening these days in pymanopt :)

Not at all! I'm happy for any suggestions so thanks for the thoughtful write-up :bow: 

The reason to configure the retraction at construction time is simply that this is the least acrobatic way of doing it here. Since retractions are pretty much only called by solvers, we'd otherwise have to provide that information a) when constructing a solver or b) when calling the `solve` method of a solver. I think configuring the retraction for a manifold is the most natural way to go about it, especially since the rotations manifold is the only one with two different retractions we have so far.

As far as renaming methods and properties goes, I think we're on the same page. Certain abbreviations such as `exp`, `log`, `dim` and `dist` are established enough to stick to them. Something like `tangent` or `transp` on the other hand may need clarification. In particular `transp` is so easily confused with `transpose` that I'd really like to be more explicit and verbose to avoid someone from having to check the docstring, documentation or worse the code itself. The same goes for argument names. Single-letter variable names are notoriously hard to keep track of (even if that's what we use in mathematical notation) so I think it's helpful to be more explicit and have something like `retr(point, tangent_vector)` rather than `retr(X, U)`. My main inspiration for the new naming scheme is actually taken from https://github.com/geomstats/geomstats who are very explicit and consistent on these points.

Lastly, I'll have to look into the way gradient conversion is done in manifolds.jl. Doesn't this approach only work for embedded submanifolds for Euclidean space though? The conversion works a bit differently for quotient manifolds. In any case, definitely sounds interesting and worth looking into. Thanks for the suggestion :+1:

**Comment by kellertuer** [comment]
Thanks for the comments and explanations.

In Manopt.jl the `solve!()` (`!` in Julia means the functions modifies its input) has two parameters, the problem (static part, functions, gradients, this stuff) and the options (parameters for the solvers) and indeed the options very often carry a retraction method inside and (if required) a vector transport.

But you are right, it is also a good model to say that the manifold might be set up to “know” this, that is just a matter of perspective I would say. In Julia the manifold is the set with all retractions and the solver has to know which one to use – here the manifold is the set with a specific retraction (similarly vector transport).

For the naming, the Julia convention on function names (and types) is to avoid abbreviations, so we have `retract` and ? vector_transport` for example. For variable names, however, we set up https://juliamanifolds.github.io/Manifolds.jl/latest/misc/notation.html – so for example points are always p and q (or p1,p2,p3,...) and so on and so forth, since most of our docstrings also contain the mathematical formula anyways (see e.g. {exp on the sphere](https://juliamanifolds.github.io/Manifolds.jl/latest/manifolds/sphere.html#Base.exp-Tuple{AbstractSphere,%20Vararg{Any,%20N}%20where%20N}) so that parameters are usually similar to math variables in Manifolds.jl. But you are right, the approach from geomstats is also nice to read (and both approaches provide the same “global consistency” of variable names).

the current name `tangent` is really a little misleading maybe, since the function name represents what is returned. We unified projections to `project(M, p)` to project p onto M and `project(M, p, X)` to project X onto TpM.
Ok to be complete we also have `project!(M,q,p)` which projects p onto M without allocating new memory but inlace of q and `project!(M,Y,p,X)` doing the projection from X onto TpM in place of Y.
This second technical detail avoids a lot of memory allocation which is one trick to get Julia methods _really_ fast.

The current approach implemented works for all manifolds that are embedded (does not matter whether isometrically or not since we can change the representer). Quotient manifolds might be different, you are right. We have an open issue https://github.com/JuliaManifolds/Manifolds.jl/issues/205 for that, since for now we do not have support for (abstract) quotient manifolds (like we have for example for embedded manifolds, Lie groups or different metric on a manifold).
But then we would just implement the gradient for this abstract type (and hence all quotient manifolds) anew.
Quotient manifolds is something I would like to look at next (implement them generically) – for now we are remodelling the interface (how general manifolds are implemented “under the hood”) but maybe I go into quotient manifolds afterwards.

**Comment by NicolasBoumal** [comment]
> In particular transp is so easily confused with transpose that I'd really like to be more explicit and verbose

I fully agree. The issue is made even worse by the fac that there is one parallel transport (uniquely defined) but also many possible vector transports (see Absil's book; that's not what we mean here) and transporters (which is what we mean; see Section 10.5 in my book and the discussion at the end of that section for a comparison with vector transports). A Riemannian manifold could have several relevant transporters implemented, just like it could have several retractions implemented.

Currently, this is all handled in a rather ad hoc way in the Matlab version of Manopt, because these things grew over time as the needs arose, and we always insisted on remaining backward compatible. I certainly agree that it makes sense to move toward more explicit and more consistent names for such objects.

About gradient and Hessian "conversions": the tricky thing here is that we must not only be explicit about how points and tangent vectors are represented for the manifold itself, but also about what the "structure space is" (either the embedding space, or the total space from a quotient), how points and tangent vectors are represented there (numerically), and what the Riemannian metrics are on both. In most cases, the embedding space is simply a Euclidean space of matrices with the standard inner product, and the manifold is a Riemannian submanifold of that. Then things are rather clear, and implementations often cater to that important special case. It also works well for simple Riemannian quotient manifolds.

**Comment by kellertuer** [comment]
I usually also call transporters vector transports. We are currently revising our ManifoldsBase.jl (interface to implement manifolds) and making that more detailed – a preview of our method is here

https://juliamanifolds.github.io/ManifoldsBase.jl/previews/PR91/vector_transports.html

(just changed that slightly yesterday, not yet published, this is a Preview), so similar to `retract` having a last argument specifying the type of retraction, the vector transports also can have a type (by default this is the parallel transport).
So as you say in Julia you can have several retractions (inverse retractions as well) or vector transports – distinguished by this last type.

In Matlab you could write a wrapper function `retract` that depending on a last parameter (string?) calls its other inner retracts which already exist. This way you would stay backward compatible, since the old functions are still there.

For the gradient – yes you are right, usually I would like to to distinguish that by using an `EmbeddedManifold(M,N)`, where you both know M and its embedding N (similarly – but not yet existing – `QuotientManifold(M,N)` which also knows its total space N).

**Review by sweichwald — APPROVED** [review]
I support the suggested improvements and API changes for upcoming Pymanopt 1.0.0.

**Pull request merged**
