### PR TITLE
Add manifold of strictly positive vectors

### PR DESCRIPTION
**Pull request by antoinecollas**
Hello,
I have implemented the manifold of strictly positive vectors which derives from the positive definite matrices. I also implemented the corresponding unit tests.

### CODE REVIEW

**Comment by sylvchev** [comment]
Thank you very much for this nice PR. Do you have an some example code and maybe a visualization to provide for the examples section?

**Comment by antoinecollas** [comment]
I have used this manifold but unfortunately I don't have any examples for the moment.

**Comment by sweichwald** [comment]
Thanks a lot for this PR, @antoinecollas ! :+1: 

This looks clean and good to me – I wouldn't want to hold this back merely for reasons of a missing example. Yet, we may want to await the backend overhaul before merging new features – @nkoep what do you think? (Sorry, have not gotten around to get up to speed with and contribute to the backend rework, yet.)

Thanks also @sylvchev – I have been struggling to keep up with all the activity on here :innocent:

**Comment by sylvchev** [comment]
My 2 cents are that this code is compatible with the new backends, as they are available in the repo right now, so I think it is safe to merge this PR (and #112 )

**Comment by sweichwald** [comment]
Thanks to both of you for contributing and reviewing @antoinecollas and @sylvchev !

**Comment by nkoep** [comment]
Sorry to raise this after such a long time, but I wasn't around when this PR got merged. I'm a little puzzled that `inner`, `norm`, `dist`, etc. return arrays, not scalars. Since there is no reference given I assumed this was supposed to be the (product manifold) of strictly positive vectors. All these methods I mentioned should still return a scalar for product manifolds though. What am I missing here @antoinecollas, @sweichwald, @sylvchev?

**Comment by antoinecollas** [comment]
This is indeed a mistake... The functions you mention should return scalars. I'll try to fix that in the next week.

**Pull request merged**
