### PR TITLE
Skew-symmetric matrices

### PR DESCRIPTION
**Pull request by AfoninAndrey**

### CODE REVIEW

**Comment by nkoep** [comment]
Hey, thanks for the PR! Looks good from what I can tell at a first glance. Just a few notes. It's probably best to keep this in the euclidean.py module seeing how it also houses the manifold of real n-by-n symmetric matrices instead of introducing a separate module. The geometry should then also be added to the import list in the manifold package's \_\_init__.py module. Please also rename the class to "SkewSymmetric" as we like to stick to the usual camel case naming convention for classes and not mix it with snake case. The RuntimeError exception that you raise in the c'tor should probably be replaced with a somewhat more appropriate ValueError. Lastly, and this is a very minor detail, but please remove superfluous parentheses around conditionals such as those in lines 19 and 23.

**Comment by AfoninAndrey** [comment]
Hello! Ok, I will do it.

**Comment by nkoep** [comment]
Looks good except for the left over Skey_Symmetric.py file. If you could remove this file, I'll merge the changes later today. Cheers!

**Comment by AfoninAndrey** [comment]
Ok, I will try a little bit later

**Pull request merged**
